name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'

    - name: Build and Test
      run: |
        xcodebuild test \
          -project ToDoListApp.xcodeproj \
          -scheme ToDoListApp \
          -destination 'id=11423FF0-DCF3-45E2-885A-9C649FF61873'
